people = [
    {
        "name": "Tim Kaechle",
        "email": "timothy.kaechle@me.com",
        "accounts": {"discord": "kaechle"},
        "locations": [
            {"current": "Recanto da Sereia, Guarapari, ES, Brazil"},
            {"from": "Ponca City, OK, USA"},
        ],
        "description": "Wannabe philosopher that's addicted to AI APIs.",
        "permissions": ["admin"],
        "interests": [
            "programming",
            "metaprogramming",
            "ai",
            "travel",
            "philosophy",
            "psychology",
        ],
        "from": "Ponca City, OK, USA",
        "age": 40,
        "annotations": [],
    },
    {
        "name": "Ken",
        "email": "",
        "accounts": {"discord": "syztem"},
        "description": "Edgelord.",
        "permissions": ["user"],
        "interests": [
            "computer hardware",
            "ai",
            "electric vehicles",
            "podcasts",
            "self development",
        ],
        "location": "Los Angeles, CA, USA",
        "from": "Los Angeles, CA, USA",
        "age": 37,
        "annotations": [],
    },
]
